"""
Build jamo reference poses from datasets/seq_*.npy.

The imported dataset stores each frame as:
  20 two-dimensional normalized bone vectors + 15 angles + label

This script converts the representative bone vectors for each jamo back into
21 hand landmarks so the existing realtime scorer can compare MediaPipe hands
against dataset-derived jamo poses.
"""
import glob
import os
import re
from pprint import pformat

import numpy as np


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET_DIR = os.path.join(BASE_DIR, "datasets")
OUTPUT_PATH = os.path.join(BASE_DIR, "pose_data.py")

PARENTS = [0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 11, 0, 13, 14, 15, 0, 17, 18, 19]
CHILDREN = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


def collect_vectors(path):
    arr = np.load(path, allow_pickle=True)
    if arr.ndim != 3 or arr.shape[-1] < 40:
        return np.empty((0, 40), dtype=np.float32)
    return arr.reshape(-1, arr.shape[-1])[:, :40].astype(np.float32)


def representative_vectors(vectors):
    if len(vectors) == 0:
        return None

    median = np.median(vectors, axis=0).reshape(20, 2)
    norms = np.linalg.norm(median, axis=1, keepdims=True)
    norms[norms < 1e-6] = 1.0
    return median / norms


def vectors_to_landmarks(vectors):
    points = np.zeros((21, 3), dtype=np.float32)

    for idx, (parent, child) in enumerate(zip(PARENTS, CHILDREN)):
        vx, vy = vectors[idx]
        points[child, 0] = points[parent, 0] + vx
        points[child, 1] = points[parent, 1] + vy

    middle_mcp = points[9]
    scale = np.linalg.norm(middle_mcp[:2])
    if scale < 1e-6:
        scale = 1.0

    # Match normalizeLandmarks(): right-hand webcam x/y are flipped for scoring.
    points[:, 0] = -points[:, 0] / scale
    points[:, 1] = -points[:, 1] / scale
    points[:, 2] = 0

    return np.round(points, 4).tolist()


def build_video_poses():
    grouped = {}
    for path in glob.glob(os.path.join(DATASET_DIR, "seq_*.npy")):
        match = re.match(r"seq_(.+?)_\d+\.npy$", os.path.basename(path))
        if not match:
            continue
        grouped.setdefault(match.group(1), []).append(path)

    poses = {}
    for jamo, paths in sorted(grouped.items()):
        all_vectors = [collect_vectors(path) for path in paths]
        all_vectors = [vectors for vectors in all_vectors if len(vectors) > 0]
        if not all_vectors:
            continue

        vectors = representative_vectors(np.concatenate(all_vectors, axis=0))
        if vectors is None:
            continue
        poses[jamo] = vectors_to_landmarks(vectors)

    return poses


def main():
    poses = build_video_poses()
    content = (
        '"""Dataset-derived jamo reference poses.\n'
        "\n"
        "Generated by scripts/build_jamo_pose_data.py from datasets/seq_*.npy.\n"
        '"""\n\n'
        f"VIDEO_POSES = {pformat(poses, width=100, sort_dicts=True)}\n"
    )

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"wrote {OUTPUT_PATH}")
    print(f"jamo poses: {len(poses)}")


if __name__ == "__main__":
    main()
